---
- name: Ensure MySQL is installed
  apt: pkg="{{ item }}" state=latest
  with_items:
    - mysql-client
    - mysql-server
  sudo: yes
  notify : restart mysql

- name: Service Mysql
  service: name=mysql state=started enabled=yes
  sudo: yes

- name: Create root MySQL users
  mysql_user: name="{{ mysql_root_user }}" password="{{ mysql_root_pass }}" host="{{ item }}" priv=*.*:ALL,GRANT state=present
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - localhost
  sudo: yes
  notify: restart mysql

- name: Copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  sudo: yes
